
export const REQUEST = "REQUEST";
export const REQUEST_EPISODES_SUCCESS = "REQUEST_EPISODES_SUCCESS";
export const REQUEST_LOCATIONS_SUCCESS = "REQUEST_LOCATIONS_SUCCESS";
export const REQUEST_CHARACTERS_SUCCESS = "REQUEST_CHARACTERS_SUCCESS";
export const REQUEST_ERROR = "REQUEST_ERROR";

export const FILTER_CHANGED = "FILTER_CHANGED";
export const PAGE_CHANGED = "PAGE_CHANGED";

export const CLEAN_ERROR = "CLEAN_ERROR";

export const UPDATE_NAME_BOX = "UPDATE_NAME_BOX";
export const ERASE_NAME_FIELD = "ERASE_NAME_FIELD";

export const UPDATE_TYPE_BOX = "UPDATE_TYPE_BOX";
export const ERASE_TYPE_FIELD = "ERASE_TYPE_FIELD";
